name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
        - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: deploy
        run:  |
          echo "should be deployed"
          echo "git ref"
          echo $GITHUB_REF
          echo "git head ref"
          echo $GITHUB_HEAD_REF
          echo "git base ref"
          echo $GITHUB_BASE_REF
          echo "git ref name"
          echo $GITHUB_REF_NAME
